///// NdefPreset('allArm') settings:
List[
	('curr' -> [ [ 'divefreq', 0.05 ], [ 'topfreq', 912.0 ], [ 'filtfreq', 41.0 ] ]), 
	('set1' -> [ [ 'divefreq', 20.0 ], [ 'topfreq', 67270.0 ], [ 'filtfreq', 136.0 ] ]), 
	('set2' -> [ [ 'divefreq', 12.97 ], [ 'topfreq', 912.0 ], [ 'filtfreq', 25599.0 ] ]), 
	('doak' -> [ [ 'divefreq', 0.06 ], [ 'topfreq', 49176.0 ], [ 'filtfreq', 2986.0 ] ]), 
	('set2333' -> [ [ 'divefreq', 0.09 ], [ 'topfreq', 68.0 ], [ 'filtfreq', 65.0 ] ]) 
]