/*
///// These are the settings for NdefPreset('xf-ringMod'):
///// you can edit the textfile, e.g. choosing better preset names,
///// tuning parameter values, or deleting unwanted presets.
///// When done, save the textfile where it is, and
///// then load the edited settings again with:
NdefPreset('xf-ringMod').loadSettings(clear: true);
*/

List[
	('curr' -> [ [ 'oct', 2 ], [ 'which', 0 ], [ 'pow', 1 ] ]) 
]

